import { ConditionFlags, IndianDish } from './types'

export const INDIAN_FOOD_DB: IndianDish[] = [
  // Breakfast dishes
  {
    id: 'moong-dal-chilla',
    name: 'Moong Dal Chilla',
    hindi_name: 'Moong Dal Chilla',
    region: ['north', 'pan-indian'],
    meal_type: ['breakfast'],
    is_vegetarian: true,
    is_vegan: false,
    allergens: [],
    per_100g: { calories: 110, protein_g: 8, carbs_g: 12, fat_g: 3, fiber_g: 2, sodium_mg: 320, potassium_mg: 180, phosphorus_mg: 120 },
    gi_index: 42,
    typical_serving_g: 150,
    cost_per_serving_inr: 15,
    prep_time_min: 10,
    condition_flags: { diabetes_safe: true, hypertension_safe: true, ckd_stage3_safe: true, ckd_stage4_safe: true, heart_safe: true },
    ingredients: ['moong dal', 'onion', 'tomato', 'ginger', 'green chili', 'oil'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=500&fit=crop',
  },
  {
    id: 'oats-upma',
    name: 'Oats Upma',
    hindi_name: 'Oats Upma',
    region: ['south', 'pan-indian'],
    meal_type: ['breakfast'],
    is_vegetarian: true,
    is_vegan: true,
    allergens: ['gluten'],
    per_100g: { calories: 95, protein_g: 4, carbs_g: 15, fat_g: 2, fiber_g: 2.5, sodium_mg: 280, potassium_mg: 120, phosphorus_mg: 100 },
    gi_index: 48,
    typical_serving_g: 200,
    cost_per_serving_inr: 12,
    prep_time_min: 8,
    condition_flags: { diabetes_safe: true, hypertension_safe: true, ckd_stage3_safe: true, ckd_stage4_safe: true, heart_safe: true },
    ingredients: ['oats', 'onion', 'carrot', 'peas', 'oil', 'salt'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1517674712202-14dd9538aa97?w=500&h=500&fit=crop',
  },
  {
    id: 'poha',
    name: 'Poha',
    hindi_name: 'Poha',
    region: ['north', 'maharashtrian'],
    meal_type: ['breakfast', 'snack'],
    is_vegetarian: true,
    is_vegan: false,
    allergens: [],
    per_100g: { calories: 110, protein_g: 2.5, carbs_g: 22, fat_g: 2, fiber_g: 1, sodium_mg: 320, potassium_mg: 140, phosphorus_mg: 80 },
    gi_index: 65,
    typical_serving_g: 150,
    cost_per_serving_inr: 10,
    prep_time_min: 8,
    condition_flags: { diabetes_safe: false, hypertension_safe: true, ckd_stage3_safe: true, ckd_stage4_safe: true, heart_safe: false },
    ingredients: ['poha', 'potato', 'onion', 'mustard seeds', 'oil', 'turmeric'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1585937421612-70a19fb1133b?w=500&h=500&fit=crop',
  },
  {
    id: 'idli-sambar',
    name: 'Idli Sambar',
    hindi_name: 'Idli Sambar',
    region: ['south'],
    meal_type: ['breakfast'],
    is_vegetarian: true,
    is_vegan: false,
    allergens: [],
    per_100g: { calories: 85, protein_g: 3, carbs_g: 16, fat_g: 1.5, fiber_g: 1.5, sodium_mg: 280, potassium_mg: 150, phosphorus_mg: 100 },
    gi_index: 50,
    typical_serving_g: 200,
    cost_per_serving_inr: 18,
    prep_time_min: 15,
    condition_flags: { diabetes_safe: true, hypertension_safe: true, ckd_stage3_safe: true, ckd_stage4_safe: true, heart_safe: true },
    ingredients: ['rice flour', 'urad dal', 'lentils', 'vegetables', 'spices'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1609501676725-7186f017a4b1?w=500&h=500&fit=crop',
  },
  {
    id: 'dosa-plain',
    name: 'Dosa Plain',
    hindi_name: 'Dosa Plain',
    region: ['south'],
    meal_type: ['breakfast'],
    is_vegetarian: true,
    is_vegan: false,
    allergens: [],
    per_100g: { calories: 120, protein_g: 3, carbs_g: 20, fat_g: 3, fiber_g: 1, sodium_mg: 250, potassium_mg: 130, phosphorus_mg: 110 },
    gi_index: 55,
    typical_serving_g: 150,
    cost_per_serving_inr: 20,
    prep_time_min: 12,
    condition_flags: { diabetes_safe: true, hypertension_safe: true, ckd_stage3_safe: true, ckd_stage4_safe: true, heart_safe: true },
    ingredients: ['rice flour', 'urad dal', 'fenugreek', 'oil'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1585829365295-c630e6ff0a5c?w=500&h=500&fit=crop',
  },
  {
    id: 'besan-chilla',
    name: 'Besan Chilla',
    hindi_name: 'Besan Chilla',
    region: ['north', 'pan-indian'],
    meal_type: ['breakfast'],
    is_vegetarian: true,
    is_vegan: false,
    allergens: [],
    per_100g: { calories: 125, protein_g: 6, carbs_g: 14, fat_g: 4.5, fiber_g: 1.5, sodium_mg: 310, potassium_mg: 160, phosphorus_mg: 140 },
    gi_index: 45,
    typical_serving_g: 150,
    cost_per_serving_inr: 12,
    prep_time_min: 8,
    condition_flags: { diabetes_safe: true, hypertension_safe: true, ckd_stage3_safe: true, ckd_stage4_safe: false, heart_safe: true },
    ingredients: ['besan', 'onion', 'tomato', 'green chili', 'oil'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=500&fit=crop',
  },
  {
    id: 'ragi-porridge',
    name: 'Ragi Porridge',
    hindi_name: 'Ragi Porridge',
    region: ['south', 'pan-indian'],
    meal_type: ['breakfast'],
    is_vegetarian: true,
    is_vegan: true,
    allergens: [],
    per_100g: { calories: 98, protein_g: 3, carbs_g: 18, fat_g: 1, fiber_g: 3, sodium_mg: 200, potassium_mg: 110, phosphorus_mg: 90 },
    gi_index: 55,
    typical_serving_g: 200,
    cost_per_serving_inr: 15,
    prep_time_min: 10,
    condition_flags: { diabetes_safe: true, hypertension_safe: true, ckd_stage3_safe: true, ckd_stage4_safe: true, heart_safe: true },
    ingredients: ['ragi flour', 'water', 'salt', 'jaggery'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1585518419759-831e26be81f6?w=500&h=500&fit=crop',
  },
  {
    id: 'sabudana-khichdi',
    name: 'Sabudana Khichdi',
    hindi_name: 'Sabudana Khichdi',
    region: ['north', 'gujarati'],
    meal_type: ['breakfast', 'snack'],
    is_vegetarian: true,
    is_vegan: false,
    allergens: [],
    per_100g: { calories: 140, protein_g: 1.5, carbs_g: 28, fat_g: 3, fiber_g: 0.5, sodium_mg: 290, potassium_mg: 100, phosphorus_mg: 60 },
    gi_index: 75,
    typical_serving_g: 120,
    cost_per_serving_inr: 14,
    prep_time_min: 15,
    condition_flags: { diabetes_safe: false, hypertension_safe: false, ckd_stage3_safe: false, ckd_stage4_safe: false, heart_safe: false },
    ingredients: ['sabudana', 'peanuts', 'potato', 'oil', 'salt'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1545456519-cf12804b5c11?w=500&h=500&fit=crop',
  },
  {
    id: 'daliya',
    name: 'Daliya',
    hindi_name: 'Daliya',
    region: ['north', 'pan-indian'],
    meal_type: ['breakfast'],
    is_vegetarian: true,
    is_vegan: true,
    allergens: ['gluten'],
    per_100g: { calories: 85, protein_g: 2.5, carbs_g: 16, fat_g: 1, fiber_g: 2, sodium_mg: 200, potassium_mg: 100, phosphorus_mg: 80 },
    gi_index: 50,
    typical_serving_g: 200,
    cost_per_serving_inr: 10,
    prep_time_min: 12,
    condition_flags: { diabetes_safe: true, hypertension_safe: true, ckd_stage3_safe: true, ckd_stage4_safe: true, heart_safe: true },
    ingredients: ['broken wheat', 'vegetables', 'oil', 'spices'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500&h=500&fit=crop',
  },
  {
    id: 'egg-white-scrambled',
    name: 'Egg White Scrambled',
    hindi_name: 'Egg White Scrambled',
    region: ['pan-indian'],
    meal_type: ['breakfast'],
    is_vegetarian: false,
    is_vegan: false,
    allergens: ['eggs'],
    per_100g: { calories: 52, protein_g: 11, carbs_g: 1, fat_g: 0.5, fiber_g: 0, sodium_mg: 170, potassium_mg: 160, phosphorus_mg: 150 },
    gi_index: 0,
    typical_serving_g: 150,
    cost_per_serving_inr: 20,
    prep_time_min: 5,
    condition_flags: { diabetes_safe: true, hypertension_safe: true, ckd_stage3_safe: false, ckd_stage4_safe: false, heart_safe: true },
    ingredients: ['egg whites', 'oil', 'salt', 'pepper'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1609501676725-7186f017a4b1?w=500&h=500&fit=crop',
  },
  {
    id: 'methi-paratha-small',
    name: 'Methi Paratha Small',
    hindi_name: 'Methi Paratha Small',
    region: ['north', 'pan-indian'],
    meal_type: ['breakfast'],
    is_vegetarian: true,
    is_vegan: false,
    allergens: ['gluten'],
    per_100g: { calories: 145, protein_g: 4, carbs_g: 18, fat_g: 6, fiber_g: 1.5, sodium_mg: 380, potassium_mg: 140, phosphorus_mg: 100 },
    gi_index: 60,
    typical_serving_g: 100,
    cost_per_serving_inr: 12,
    prep_time_min: 10,
    condition_flags: { diabetes_safe: false, hypertension_safe: false, ckd_stage3_safe: true, ckd_stage4_safe: true, heart_safe: false },
    ingredients: ['atta', 'methi', 'oil', 'salt'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1515521396207-6211f368b3a6?w=500&h=500&fit=crop',
  },
  {
    id: 'upma',
    name: 'Upma',
    hindi_name: 'Upma',
    region: ['south', 'pan-indian'],
    meal_type: ['breakfast'],
    is_vegetarian: true,
    is_vegan: false,
    allergens: [],
    per_100g: { calories: 92, protein_g: 2.5, carbs_g: 10, fat_g: 4, fiber_g: 1, sodium_mg: 300, potassium_mg: 100, phosphorus_mg: 80 },
    gi_index: 45,
    typical_serving_g: 150,
    cost_per_serving_inr: 12,
    prep_time_min: 8,
    condition_flags: { diabetes_safe: true, hypertension_safe: true, ckd_stage3_safe: true, ckd_stage4_safe: true, heart_safe: true },
    ingredients: ['semolina', 'vegetables', 'mustard seeds', 'oil'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1585937421612-70a19fb1133b?w=500&h=500&fit=crop',
  },
  {
    id: 'steamed-dhokla',
    name: 'Steamed Dhokla',
    hindi_name: 'Steamed Dhokla',
    region: ['gujarati', 'pan-indian'],
    meal_type: ['breakfast', 'snack'],
    is_vegetarian: true,
    is_vegan: false,
    allergens: [],
    per_100g: { calories: 78, protein_g: 2.5, carbs_g: 14, fat_g: 1.5, fiber_g: 1, sodium_mg: 310, potassium_mg: 120, phosphorus_mg: 90 },
    gi_index: 48,
    typical_serving_g: 100,
    cost_per_serving_inr: 15,
    prep_time_min: 20,
    condition_flags: { diabetes_safe: true, hypertension_safe: true, ckd_stage3_safe: true, ckd_stage4_safe: true, heart_safe: true },
    ingredients: ['besan', 'rice flour', 'yogurt', 'ginger', 'oil'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1585937421612-70a19fb1133b?w=500&h=500&fit=crop',
  },
  {
    id: 'vermicelli-upma',
    name: 'Vermicelli Upma',
    hindi_name: 'Vermicelli Upma',
    region: ['south', 'pan-indian'],
    meal_type: ['breakfast'],
    is_vegetarian: true,
    is_vegan: false,
    allergens: ['gluten'],
    per_100g: { calories: 105, protein_g: 2, carbs_g: 18, fat_g: 2.5, fiber_g: 0.5, sodium_mg: 280, potassium_mg: 90, phosphorus_mg: 70 },
    gi_index: 62,
    typical_serving_g: 150,
    cost_per_serving_inr: 13,
    prep_time_min: 10,
    condition_flags: { diabetes_safe: false, hypertension_safe: true, ckd_stage3_safe: true, ckd_stage4_safe: true, heart_safe: false },
    ingredients: ['vermicelli', 'peas', 'carrot', 'oil', 'spices'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=500&h=500&fit=crop',
  },

  // Lunch/Dinner dishes
  {
    id: 'dal-tadka',
    name: 'Dal Tadka',
    hindi_name: 'Dal Tadka',
    region: ['north', 'pan-indian'],
    meal_type: ['lunch', 'dinner'],
    is_vegetarian: true,
    is_vegan: true,
    allergens: [],
    per_100g: { calories: 72, protein_g: 5.5, carbs_g: 11, fat_g: 1, fiber_g: 2, sodium_mg: 280, potassium_mg: 250, phosphorus_mg: 130 },
    gi_index: 32,
    typical_serving_g: 200,
    cost_per_serving_inr: 18,
    prep_time_min: 25,
    condition_flags: { diabetes_safe: true, hypertension_safe: true, ckd_stage3_safe: false, ckd_stage4_safe: false, heart_safe: true },
    ingredients: ['moong dal', 'toor dal', 'tomato', 'onion', 'spices', 'ghee'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=500&fit=crop',
  },
  {
    id: 'moong-dal',
    name: 'Moong Dal',
    hindi_name: 'Moong Dal',
    region: ['pan-indian'],
    meal_type: ['lunch', 'dinner'],
    is_vegetarian: true,
    is_vegan: true,
    allergens: [],
    per_100g: { calories: 75, protein_g: 6, carbs_g: 12, fat_g: 1.5, fiber_g: 2.5, sodium_mg: 270, potassium_mg: 280, phosphorus_mg: 140 },
    gi_index: 32,
    typical_serving_g: 200,
    cost_per_serving_inr: 16,
    prep_time_min: 20,
    condition_flags: { diabetes_safe: true, hypertension_safe: true, ckd_stage3_safe: false, ckd_stage4_safe: false, heart_safe: true },
    ingredients: ['moong dal', 'water', 'turmeric', 'salt', 'oil'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=500&fit=crop',
  },
  {
    id: 'chana-dal',
    name: 'Chana Dal',
    hindi_name: 'Chana Dal',
    region: ['pan-indian'],
    meal_type: ['lunch', 'dinner'],
    is_vegetarian: true,
    is_vegan: true,
    allergens: [],
    per_100g: { calories: 82, protein_g: 7, carbs_g: 14, fat_g: 1.5, fiber_g: 3, sodium_mg: 260, potassium_mg: 320, phosphorus_mg: 160 },
    gi_index: 35,
    typical_serving_g: 200,
    cost_per_serving_inr: 15,
    prep_time_min: 25,
    condition_flags: { diabetes_safe: true, hypertension_safe: false, ckd_stage3_safe: false, ckd_stage4_safe: false, heart_safe: true },
    ingredients: ['chana dal', 'water', 'turmeric', 'onion', 'oil'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=500&fit=crop',
  },
  {
    id: 'rajma',
    name: 'Rajma',
    hindi_name: 'Rajma',
    region: ['north', 'pan-indian'],
    meal_type: ['lunch', 'dinner'],
    is_vegetarian: true,
    is_vegan: true,
    allergens: [],
    per_100g: { calories: 80, protein_g: 6, carbs_g: 14, fat_g: 1, fiber_g: 3, sodium_mg: 380, potassium_mg: 450, phosphorus_mg: 140 },
    gi_index: 40,
    typical_serving_g: 200,
    cost_per_serving_inr: 20,
    prep_time_min: 30,
    condition_flags: { diabetes_safe: true, hypertension_safe: false, ckd_stage3_safe: false, ckd_stage4_safe: false, heart_safe: true },
    ingredients: ['kidney beans', 'tomato', 'onion', 'spices', 'oil'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1585937421612-70a19fb1133b?w=500&h=500&fit=crop',
  },
  {
    id: 'dal-makhani',
    name: 'Dal Makhani',
    hindi_name: 'Dal Makhani',
    region: ['north', 'pan-indian'],
    meal_type: ['lunch', 'dinner'],
    is_vegetarian: true,
    is_vegan: false,
    allergens: ['dairy'],
    per_100g: { calories: 125, protein_g: 6, carbs_g: 12, fat_g: 6, fiber_g: 2, sodium_mg: 320, potassium_mg: 200, phosphorus_mg: 120 },
    gi_index: 38,
    typical_serving_g: 150,
    cost_per_serving_inr: 35,
    prep_time_min: 45,
    condition_flags: { diabetes_safe: true, hypertension_safe: false, ckd_stage3_safe: true, ckd_stage4_safe: true, heart_safe: false },
    ingredients: ['urad dal', 'rajma', 'butter', 'cream', 'tomato', 'spices'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=500&fit=crop',
  },
  {
    id: 'kadhi',
    name: 'Kadhi',
    hindi_name: 'Kadhi',
    region: ['north', 'gujarati', 'pan-indian'],
    meal_type: ['lunch', 'dinner'],
    is_vegetarian: true,
    is_vegan: false,
    allergens: ['dairy'],
    per_100g: { calories: 68, protein_g: 3.5, carbs_g: 8, fat_g: 2.5, fiber_g: 0.5, sodium_mg: 310, potassium_mg: 180, phosphorus_mg: 100 },
    gi_index: 35,
    typical_serving_g: 250,
    cost_per_serving_inr: 16,
    prep_time_min: 20,
    condition_flags: { diabetes_safe: true, hypertension_safe: true, ckd_stage3_safe: true, ckd_stage4_safe: true, heart_safe: true },
    ingredients: ['yogurt', 'besan', 'turmeric', 'ginger', 'fenugreek leaves', 'oil'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1585937421612-70a19fb1133b?w=500&h=500&fit=crop',
  },
  {
    id: 'palak-paneer-small',
    name: 'Palak Paneer Small',
    hindi_name: 'Palak Paneer Small',
    region: ['north', 'pan-indian'],
    meal_type: ['lunch', 'dinner'],
    is_vegetarian: true,
    is_vegan: false,
    allergens: ['dairy'],
    per_100g: { calories: 110, protein_g: 8, carbs_g: 5, fat_g: 7, fiber_g: 1.5, sodium_mg: 420, potassium_mg: 420, phosphorus_mg: 180 },
    gi_index: 20,
    typical_serving_g: 120,
    cost_per_serving_inr: 32,
    prep_time_min: 20,
    condition_flags: { diabetes_safe: true, hypertension_safe: false, ckd_stage3_safe: false, ckd_stage4_safe: false, heart_safe: true },
    ingredients: ['spinach', 'paneer', 'cream', 'ginger', 'garlic', 'oil'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=500&fit=crop',
  },
  {
    id: 'paneer-bhurji',
    name: 'Paneer Bhurji',
    hindi_name: 'Paneer Bhurji',
    region: ['north', 'pan-indian'],
    meal_type: ['lunch', 'dinner'],
    is_vegetarian: true,
    is_vegan: false,
    allergens: ['dairy'],
    per_100g: { calories: 125, protein_g: 12, carbs_g: 3, fat_g: 7, fiber_g: 1, sodium_mg: 380, potassium_mg: 160, phosphorus_mg: 200 },
    gi_index: 15,
    typical_serving_g: 120,
    cost_per_serving_inr: 28,
    prep_time_min: 12,
    condition_flags: { diabetes_safe: true, hypertension_safe: false, ckd_stage3_safe: false, ckd_stage4_safe: false, heart_safe: true },
    ingredients: ['paneer', 'onion', 'tomato', 'green chili', 'oil'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=500&fit=crop',
  },
  {
    id: 'tofu-stir-fry',
    name: 'Tofu Stir Fry',
    hindi_name: 'Tofu Stir Fry',
    region: ['pan-indian'],
    meal_type: ['lunch', 'dinner'],
    is_vegetarian: true,
    is_vegan: true,
    allergens: ['soy'],
    per_100g: { calories: 95, protein_g: 15, carbs_g: 2, fat_g: 4, fiber_g: 1, sodium_mg: 320, potassium_mg: 200, phosphorus_mg: 140 },
    gi_index: 15,
    typical_serving_g: 150,
    cost_per_serving_inr: 30,
    prep_time_min: 15,
    condition_flags: { diabetes_safe: true, hypertension_safe: true, ckd_stage3_safe: false, ckd_stage4_safe: false, heart_safe: true },
    ingredients: ['tofu', 'vegetables', 'soy sauce', 'ginger', 'garlic', 'oil'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=500&fit=crop',
  },
  {
    id: 'egg-curry',
    name: 'Egg Curry',
    hindi_name: 'Egg Curry',
    region: ['pan-indian'],
    meal_type: ['lunch', 'dinner'],
    is_vegetarian: false,
    is_vegan: false,
    allergens: ['eggs'],
    per_100g: { calories: 115, protein_g: 11, carbs_g: 4, fat_g: 6, fiber_g: 0.5, sodium_mg: 380, potassium_mg: 200, phosphorus_mg: 180 },
    gi_index: 20,
    typical_serving_g: 150,
    cost_per_serving_inr: 25,
    prep_time_min: 18,
    condition_flags: { diabetes_safe: true, hypertension_safe: false, ckd_stage3_safe: false, ckd_stage4_safe: false, heart_safe: false },
    ingredients: ['eggs', 'tomato', 'onion', 'ginger', 'garlic', 'spices', 'oil'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=500&fit=crop',
  },
  {
    id: 'chicken-grilled',
    name: 'Chicken Grilled',
    hindi_name: 'Chicken Grilled',
    region: ['pan-indian'],
    meal_type: ['lunch', 'dinner'],
    is_vegetarian: false,
    is_vegan: false,
    allergens: [],
    per_100g: { calories: 125, protein_g: 26, carbs_g: 2, fat_g: 2, fiber_g: 0, sodium_mg: 320, potassium_mg: 280, phosphorus_mg: 220 },
    gi_index: 0,
    typical_serving_g: 150,
    cost_per_serving_inr: 45,
    prep_time_min: 20,
    condition_flags: { diabetes_safe: true, hypertension_safe: true, ckd_stage3_safe: false, ckd_stage4_safe: false, heart_safe: true },
    ingredients: ['chicken breast', 'yogurt', 'ginger', 'garlic', 'spices'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=500&fit=crop',
  },
  {
    id: 'fish-curry-rohu',
    name: 'Fish Curry Rohu',
    hindi_name: 'Fish Curry Rohu',
    region: ['south', 'bengali', 'pan-indian'],
    meal_type: ['lunch', 'dinner'],
    is_vegetarian: false,
    is_vegan: false,
    allergens: ['fish'],
    per_100g: { calories: 105, protein_g: 20, carbs_g: 2, fat_g: 2.5, fiber_g: 0, sodium_mg: 380, potassium_mg: 320, phosphorus_mg: 200 },
    gi_index: 0,
    typical_serving_g: 150,
    cost_per_serving_inr: 40,
    prep_time_min: 20,
    condition_flags: { diabetes_safe: true, hypertension_safe: true, ckd_stage3_safe: false, ckd_stage4_safe: false, heart_safe: true },
    ingredients: ['rohu fish', 'tomato', 'onion', 'coconut', 'spices', 'oil'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=500&fit=crop',
  },
  {
    id: 'steamed-rice',
    name: 'Steamed Rice',
    hindi_name: 'Steamed Rice',
    region: ['pan-indian'],
    meal_type: ['lunch', 'dinner'],
    is_vegetarian: true,
    is_vegan: true,
    allergens: [],
    per_100g: { calories: 130, protein_g: 2.5, carbs_g: 28, fat_g: 0.3, fiber_g: 0.4, sodium_mg: 50, potassium_mg: 50, phosphorus_mg: 40 },
    gi_index: 72,
    typical_serving_g: 150,
    cost_per_serving_inr: 8,
    prep_time_min: 15,
    condition_flags: { diabetes_safe: false, hypertension_safe: true, ckd_stage3_safe: true, ckd_stage4_safe: true, heart_safe: false },
    ingredients: ['rice', 'water', 'salt'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1585937421612-70a19fb1133b?w=500&h=500&fit=crop',
  },
  {
    id: 'brown-rice',
    name: 'Brown Rice',
    hindi_name: 'Brown Rice',
    region: ['pan-indian'],
    meal_type: ['lunch', 'dinner'],
    is_vegetarian: true,
    is_vegan: true,
    allergens: [],
    per_100g: { calories: 112, protein_g: 2.6, carbs_g: 23, fat_g: 1, fiber_g: 1.8, sodium_mg: 40, potassium_mg: 80, phosphorus_mg: 60 },
    gi_index: 58,
    typical_serving_g: 150,
    cost_per_serving_inr: 12,
    prep_time_min: 25,
    condition_flags: { diabetes_safe: true, hypertension_safe: true, ckd_stage3_safe: true, ckd_stage4_safe: true, heart_safe: true },
    ingredients: ['brown rice', 'water', 'salt'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1585937421612-70a19fb1133b?w=500&h=500&fit=crop',
  },
  {
    id: 'jeera-rice',
    name: 'Jeera Rice',
    hindi_name: 'Jeera Rice',
    region: ['north', 'pan-indian'],
    meal_type: ['lunch', 'dinner'],
    is_vegetarian: true,
    is_vegan: true,
    allergens: [],
    per_100g: { calories: 135, protein_g: 2.5, carbs_g: 28, fat_g: 1.5, fiber_g: 0.5, sodium_mg: 280, potassium_mg: 60, phosphorus_mg: 50 },
    gi_index: 70,
    typical_serving_g: 120,
    cost_per_serving_inr: 10,
    prep_time_min: 15,
    condition_flags: { diabetes_safe: false, hypertension_safe: false, ckd_stage3_safe: true, ckd_stage4_safe: true, heart_safe: false },
    ingredients: ['rice', 'jeera', 'ghee', 'salt', 'water'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1585937421612-70a19fb1133b?w=500&h=500&fit=crop',
  },
  {
    id: 'roti-1-medium',
    name: 'Roti 1 Medium',
    hindi_name: 'Roti 1 Medium',
    region: ['north', 'pan-indian'],
    meal_type: ['lunch', 'dinner'],
    is_vegetarian: true,
    is_vegan: true,
    allergens: ['gluten'],
    per_100g: { calories: 215, protein_g: 8, carbs_g: 43, fat_g: 1, fiber_g: 2, sodium_mg: 360, potassium_mg: 100, phosphorus_mg: 120 },
    gi_index: 75,
    typical_serving_g: 50,
    cost_per_serving_inr: 4,
    prep_time_min: 3,
    condition_flags: { diabetes_safe: false, hypertension_safe: true, ckd_stage3_safe: true, ckd_stage4_safe: true, heart_safe: false },
    ingredients: ['atta', 'water', 'salt', 'oil'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1585937421612-70a19fb1133b?w=500&h=500&fit=crop',
  },
  {
    id: 'phulka',
    name: 'Phulka',
    hindi_name: 'Phulka',
    region: ['north', 'pan-indian'],
    meal_type: ['lunch', 'dinner'],
    is_vegetarian: true,
    is_vegan: true,
    allergens: ['gluten'],
    per_100g: { calories: 200, protein_g: 8, carbs_g: 40, fat_g: 0.5, fiber_g: 2, sodium_mg: 350, potassium_mg: 95, phosphorus_mg: 110 },
    gi_index: 75,
    typical_serving_g: 50,
    cost_per_serving_inr: 3,
    prep_time_min: 3,
    condition_flags: { diabetes_safe: false, hypertension_safe: true, ckd_stage3_safe: true, ckd_stage4_safe: true, heart_safe: false },
    ingredients: ['atta', 'water', 'salt'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1585937421612-70a19fb1133b?w=500&h=500&fit=crop',
  },
  {
    id: 'missi-roti',
    name: 'Missi Roti',
    hindi_name: 'Missi Roti',
    region: ['north', 'pan-indian'],
    meal_type: ['lunch', 'dinner'],
    is_vegetarian: true,
    is_vegan: false,
    allergens: ['gluten'],
    per_100g: { calories: 195, protein_g: 7, carbs_g: 35, fat_g: 4, fiber_g: 2, sodium_mg: 390, potassium_mg: 150, phosphorus_mg: 130 },
    gi_index: 70,
    typical_serving_g: 60,
    cost_per_serving_inr: 8,
    prep_time_min: 8,
    condition_flags: { diabetes_safe: false, hypertension_safe: false, ckd_stage3_safe: true, ckd_stage4_safe: true, heart_safe: true },
    ingredients: ['atta', 'besan', 'water', 'onion', 'oil'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1585937421612-70a19fb1133b?w=500&h=500&fit=crop',
  },
  {
    id: 'khichdi-vegetable',
    name: 'Khichdi Vegetable',
    hindi_name: 'Khichdi Vegetable',
    region: ['north', 'pan-indian'],
    meal_type: ['lunch', 'dinner'],
    is_vegetarian: true,
    is_vegan: true,
    allergens: [],
    per_100g: { calories: 85, protein_g: 3, carbs_g: 16, fat_g: 1.5, fiber_g: 1.5, sodium_mg: 240, potassium_mg: 120, phosphorus_mg: 100 },
    gi_index: 52,
    typical_serving_g: 200,
    cost_per_serving_inr: 18,
    prep_time_min: 20,
    condition_flags: { diabetes_safe: true, hypertension_safe: true, ckd_stage3_safe: true, ckd_stage4_safe: true, heart_safe: true },
    ingredients: ['rice', 'moong dal', 'vegetables', 'turmeric', 'oil'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1585937421612-70a19fb1133b?w=500&h=500&fit=crop',
  },
  {
    id: 'moong-khichdi',
    name: 'Moong Khichdi',
    hindi_name: 'Moong Khichdi',
    region: ['north', 'pan-indian'],
    meal_type: ['lunch', 'dinner'],
    is_vegetarian: true,
    is_vegan: true,
    allergens: [],
    per_100g: { calories: 88, protein_g: 4, carbs_g: 15, fat_g: 1, fiber_g: 1.5, sodium_mg: 250, potassium_mg: 140, phosphorus_mg: 110 },
    gi_index: 50,
    typical_serving_g: 200,
    cost_per_serving_inr: 16,
    prep_time_min: 18,
    condition_flags: { diabetes_safe: true, hypertension_safe: true, ckd_stage3_safe: true, ckd_stage4_safe: true, heart_safe: true },
    ingredients: ['rice', 'moong dal', 'ghee', 'turmeric', 'oil'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1585937421612-70a19fb1133b?w=500&h=500&fit=crop',
  },
  {
    id: 'curd-rice',
    name: 'Curd Rice',
    hindi_name: 'Curd Rice',
    region: ['south', 'pan-indian'],
    meal_type: ['lunch', 'dinner'],
    is_vegetarian: true,
    is_vegan: false,
    allergens: ['dairy'],
    per_100g: { calories: 95, protein_g: 3.5, carbs_g: 15, fat_g: 2, fiber_g: 0, sodium_mg: 320, potassium_mg: 110, phosphorus_mg: 100 },
    gi_index: 60,
    typical_serving_g: 200,
    cost_per_serving_inr: 14,
    prep_time_min: 10,
    condition_flags: { diabetes_safe: false, hypertension_safe: true, ckd_stage3_safe: true, ckd_stage4_safe: true, heart_safe: true },
    ingredients: ['rice', 'yogurt', 'salt', 'pepper'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1585937421612-70a19fb1133b?w=500&h=500&fit=crop',
  },
  {
    id: 'sambar',
    name: 'Sambar',
    hindi_name: 'Sambar',
    region: ['south', 'pan-indian'],
    meal_type: ['lunch', 'dinner'],
    is_vegetarian: true,
    is_vegan: true,
    allergens: [],
    per_100g: { calories: 68, protein_g: 4, carbs_g: 10, fat_g: 1.5, fiber_g: 2, sodium_mg: 310, potassium_mg: 280, phosphorus_mg: 120 },
    gi_index: 40,
    typical_serving_g: 250,
    cost_per_serving_inr: 15,
    prep_time_min: 25,
    condition_flags: { diabetes_safe: true, hypertension_safe: false, ckd_stage3_safe: false, ckd_stage4_safe: false, heart_safe: true },
    ingredients: ['toor dal', 'vegetables', 'tamarind', 'spices', 'oil'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1585937421612-70a19fb1133b?w=500&h=500&fit=crop',
  },
  {
    id: 'rasam',
    name: 'Rasam',
    hindi_name: 'Rasam',
    region: ['south', 'pan-indian'],
    meal_type: ['lunch', 'dinner'],
    is_vegetarian: true,
    is_vegan: true,
    allergens: [],
    per_100g: { calories: 45, protein_g: 1.5, carbs_g: 8, fat_g: 1, fiber_g: 1, sodium_mg: 400, potassium_mg: 200, phosphorus_mg: 80 },
    gi_index: 35,
    typical_serving_g: 250,
    cost_per_serving_inr: 12,
    prep_time_min: 20,
    condition_flags: { diabetes_safe: true, hypertension_safe: false, ckd_stage3_safe: true, ckd_stage4_safe: true, heart_safe: true },
    ingredients: ['tomato', 'toor dal', 'tamarind', 'spices', 'oil'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1585937421612-70a19fb1133b?w=500&h=500&fit=crop',
  },
  {
    id: 'baingan-bharta',
    name: 'Baingan Bharta',
    hindi_name: 'Baingan Bharta',
    region: ['north', 'bengali', 'pan-indian'],
    meal_type: ['lunch', 'dinner'],
    is_vegetarian: true,
    is_vegan: true,
    allergens: [],
    per_100g: { calories: 65, protein_g: 1.5, carbs_g: 8, fat_g: 3, fiber_g: 1.5, sodium_mg: 310, potassium_mg: 180, phosphorus_mg: 60 },
    gi_index: 30,
    typical_serving_g: 200,
    cost_per_serving_inr: 14,
    prep_time_min: 15,
    condition_flags: { diabetes_safe: true, hypertension_safe: true, ckd_stage3_safe: true, ckd_stage4_safe: true, heart_safe: true },
    ingredients: ['eggplant', 'tomato', 'onion', 'oil', 'spices'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1585937421612-70a19fb1133b?w=500&h=500&fit=crop',
  },
  {
    id: 'lauki-sabzi',
    name: 'Lauki Sabzi',
    hindi_name: 'Lauki Sabzi',
    region: ['north', 'pan-indian'],
    meal_type: ['lunch', 'dinner'],
    is_vegetarian: true,
    is_vegan: true,
    allergens: [],
    per_100g: { calories: 55, protein_g: 1.2, carbs_g: 8, fat_g: 2, fiber_g: 1.2, sodium_mg: 280, potassium_mg: 140, phosphorus_mg: 50 },
    gi_index: 25,
    typical_serving_g: 200,
    cost_per_serving_inr: 12,
    prep_time_min: 12,
    condition_flags: { diabetes_safe: true, hypertension_safe: true, ckd_stage3_safe: true, ckd_stage4_safe: true, heart_safe: true },
    ingredients: ['bottle gourd', 'onion', 'oil', 'spices'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1585937421612-70a19fb1133b?w=500&h=500&fit=crop',
  },
  {
    id: 'tinda-sabzi',
    name: 'Tinda Sabzi',
    hindi_name: 'Tinda Sabzi',
    region: ['north', 'pan-indian'],
    meal_type: ['lunch', 'dinner'],
    is_vegetarian: true,
    is_vegan: true,
    allergens: [],
    per_100g: { calories: 48, protein_g: 1, carbs_g: 7, fat_g: 1.5, fiber_g: 1, sodium_mg: 260, potassium_mg: 130, phosphorus_mg: 45 },
    gi_index: 22,
    typical_serving_g: 200,
    cost_per_serving_inr: 11,
    prep_time_min: 10,
    condition_flags: { diabetes_safe: true, hypertension_safe: true, ckd_stage3_safe: true, ckd_stage4_safe: true, heart_safe: true },
    ingredients: ['round squash', 'onion', 'oil', 'turmeric'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1585937421612-70a19fb1133b?w=500&h=500&fit=crop',
  },
  {
    id: 'turai-sabzi',
    name: 'Turai Sabzi',
    hindi_name: 'Turai Sabzi',
    region: ['north', 'pan-indian'],
    meal_type: ['lunch', 'dinner'],
    is_vegetarian: true,
    is_vegan: true,
    allergens: [],
    per_100g: { calories: 52, protein_g: 1.5, carbs_g: 8, fat_g: 1.8, fiber_g: 1.5, sodium_mg: 270, potassium_mg: 160, phosphorus_mg: 55 },
    gi_index: 25,
    typical_serving_g: 200,
    cost_per_serving_inr: 13,
    prep_time_min: 12,
    condition_flags: { diabetes_safe: true, hypertension_safe: true, ckd_stage3_safe: true, ckd_stage4_safe: true, heart_safe: true },
    ingredients: ['ridge gourd', 'onion', 'tomato', 'oil'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1585937421612-70a19fb1133b?w=500&h=500&fit=crop',
  },
  {
    id: 'gobhi-sabzi-low-potassium',
    name: 'Gobhi Sabzi Low Potassium',
    hindi_name: 'Gobhi Sabzi Low Potassium',
    region: ['north', 'pan-indian'],
    meal_type: ['lunch', 'dinner'],
    is_vegetarian: true,
    is_vegan: true,
    allergens: [],
    per_100g: { calories: 40, protein_g: 1.5, carbs_g: 6, fat_g: 1.5, fiber_g: 1.2, sodium_mg: 280, potassium_mg: 100, phosphorus_mg: 40 },
    gi_index: 20,
    typical_serving_g: 200,
    cost_per_serving_inr: 10,
    prep_time_min: 10,
    condition_flags: { diabetes_safe: true, hypertension_safe: true, ckd_stage3_safe: true, ckd_stage4_safe: true, heart_safe: true },
    ingredients: ['cabbage', 'onion', 'oil', 'mustard seeds'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1585937421612-70a19fb1133b?w=500&h=500&fit=crop',
  },
  {
    id: 'beans-sabzi',
    name: 'Beans Sabzi',
    hindi_name: 'Beans Sabzi',
    region: ['north', 'pan-indian'],
    meal_type: ['lunch', 'dinner'],
    is_vegetarian: true,
    is_vegan: true,
    allergens: [],
    per_100g: { calories: 58, protein_g: 2, carbs_g: 10, fat_g: 1.5, fiber_g: 2, sodium_mg: 290, potassium_mg: 200, phosphorus_mg: 70 },
    gi_index: 30,
    typical_serving_g: 150,
    cost_per_serving_inr: 15,
    prep_time_min: 10,
    condition_flags: { diabetes_safe: true, hypertension_safe: true, ckd_stage3_safe: true, ckd_stage4_safe: true, heart_safe: true },
    ingredients: ['green beans', 'onion', 'oil', 'spices'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1585937421612-70a19fb1133b?w=500&h=500&fit=crop',
  },
  {
    id: 'karela-sabzi-diabetes-excellent',
    name: 'Karela Sabzi Diabetes Excellent',
    hindi_name: 'Karela Sabzi Diabetes Excellent',
    region: ['north', 'pan-indian'],
    meal_type: ['lunch', 'dinner'],
    is_vegetarian: true,
    is_vegan: true,
    allergens: [],
    per_100g: { calories: 42, protein_g: 1.8, carbs_g: 7, fat_g: 1, fiber_g: 2, sodium_mg: 310, potassium_mg: 180, phosphorus_mg: 60 },
    gi_index: 15,
    typical_serving_g: 150,
    cost_per_serving_inr: 14,
    prep_time_min: 12,
    condition_flags: { diabetes_safe: true, hypertension_safe: true, ckd_stage3_safe: true, ckd_stage4_safe: true, heart_safe: true },
    ingredients: ['bitter gourd', 'onion', 'oil', 'spices'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1585937421612-70a19fb1133b?w=500&h=500&fit=crop',
  },
  {
    id: 'methi-sabzi',
    name: 'Methi Sabzi',
    hindi_name: 'Methi Sabzi',
    region: ['north', 'pan-indian'],
    meal_type: ['lunch', 'dinner'],
    is_vegetarian: true,
    is_vegan: true,
    allergens: [],
    per_100g: { calories: 38, protein_g: 3, carbs_g: 5, fat_g: 1.5, fiber_g: 1.5, sodium_mg: 300, potassium_mg: 200, phosphorus_mg: 70 },
    gi_index: 20,
    typical_serving_g: 150,
    cost_per_serving_inr: 12,
    prep_time_min: 8,
    condition_flags: { diabetes_safe: true, hypertension_safe: true, ckd_stage3_safe: true, ckd_stage4_safe: true, heart_safe: true },
    ingredients: ['fenugreek leaves', 'onion', 'oil', 'salt'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1585937421612-70a19fb1133b?w=500&h=500&fit=crop',
  },
  {
    id: 'palak-soup',
    name: 'Palak Soup',
    hindi_name: 'Palak Soup',
    region: ['north', 'pan-indian'],
    meal_type: ['lunch', 'dinner'],
    is_vegetarian: true,
    is_vegan: true,
    allergens: [],
    per_100g: { calories: 48, protein_g: 2, carbs_g: 6, fat_g: 1.5, fiber_g: 1.2, sodium_mg: 320, potassium_mg: 280, phosphorus_mg: 80 },
    gi_index: 20,
    typical_serving_g: 250,
    cost_per_serving_inr: 12,
    prep_time_min: 15,
    condition_flags: { diabetes_safe: true, hypertension_safe: false, ckd_stage3_safe: false, ckd_stage4_safe: false, heart_safe: true },
    ingredients: ['spinach', 'ginger', 'garlic', 'oil', 'spices'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1585937421612-70a19fb1133b?w=500&h=500&fit=crop',
  },
  {
    id: 'tomato-soup-small',
    name: 'Tomato Soup Small',
    hindi_name: 'Tomato Soup Small',
    region: ['north', 'pan-indian'],
    meal_type: ['lunch', 'dinner'],
    is_vegetarian: true,
    is_vegan: true,
    allergens: [],
    per_100g: { calories: 35, protein_g: 1, carbs_g: 6, fat_g: 1, fiber_g: 0.8, sodium_mg: 380, potassium_mg: 150, phosphorus_mg: 40 },
    gi_index: 25,
    typical_serving_g: 200,
    cost_per_serving_inr: 11,
    prep_time_min: 12,
    condition_flags: { diabetes_safe: true, hypertension_safe: false, ckd_stage3_safe: true, ckd_stage4_safe: true, heart_safe: true },
    ingredients: ['tomato', 'onion', 'oil', 'spices'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1585937421612-70a19fb1133b?w=500&h=500&fit=crop',
  },
  {
    id: 'mixed-vegetable-curry',
    name: 'Mixed Vegetable Curry',
    hindi_name: 'Mixed Vegetable Curry',
    region: ['north', 'pan-indian'],
    meal_type: ['lunch', 'dinner'],
    is_vegetarian: true,
    is_vegan: true,
    allergens: [],
    per_100g: { calories: 70, protein_g: 2, carbs_g: 10, fat_g: 2.5, fiber_g: 1.5, sodium_mg: 300, potassium_mg: 180, phosphorus_mg: 70 },
    gi_index: 35,
    typical_serving_g: 200,
    cost_per_serving_inr: 16,
    prep_time_min: 18,
    condition_flags: { diabetes_safe: true, hypertension_safe: true, ckd_stage3_safe: true, ckd_stage4_safe: true, heart_safe: true },
    ingredients: ['mixed vegetables', 'tomato', 'onion', 'oil', 'spices'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1585937421612-70a19fb1133b?w=500&h=500&fit=crop',
  },
  {
    id: 'cabbage-stir-fry',
    name: 'Cabbage Stir Fry',
    hindi_name: 'Cabbage Stir Fry',
    region: ['pan-indian'],
    meal_type: ['lunch', 'dinner'],
    is_vegetarian: true,
    is_vegan: true,
    allergens: [],
    per_100g: { calories: 58, protein_g: 1.5, carbs_g: 8, fat_g: 2.5, fiber_g: 1.5, sodium_mg: 310, potassium_mg: 110, phosphorus_mg: 50 },
    gi_index: 22,
    typical_serving_g: 180,
    cost_per_serving_inr: 12,
    prep_time_min: 10,
    condition_flags: { diabetes_safe: true, hypertension_safe: true, ckd_stage3_safe: true, ckd_stage4_safe: true, heart_safe: true },
    ingredients: ['cabbage', 'carrot', 'oil', 'spices'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1585937421612-70a19fb1133b?w=500&h=500&fit=crop',
  },
  {
    id: 'cucumber-raita',
    name: 'Cucumber Raita',
    hindi_name: 'Cucumber Raita',
    region: ['north', 'pan-indian'],
    meal_type: ['lunch', 'dinner', 'snack'],
    is_vegetarian: true,
    is_vegan: false,
    allergens: ['dairy'],
    per_100g: { calories: 50, protein_g: 1.5, carbs_g: 4, fat_g: 2, fiber_g: 0.5, sodium_mg: 300, potassium_mg: 140, phosphorus_mg: 80 },
    gi_index: 15,
    typical_serving_g: 150,
    cost_per_serving_inr: 10,
    prep_time_min: 5,
    condition_flags: { diabetes_safe: true, hypertension_safe: true, ckd_stage3_safe: true, ckd_stage4_safe: true, heart_safe: true },
    ingredients: ['cucumber', 'yogurt', 'cumin', 'salt'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1585937421612-70a19fb1133b?w=500&h=500&fit=crop',
  },
  {
    id: 'plain-dahi-low-fat',
    name: 'Plain Dahi Low Fat',
    hindi_name: 'Plain Dahi Low Fat',
    region: ['pan-indian'],
    meal_type: ['lunch', 'dinner', 'snack'],
    is_vegetarian: true,
    is_vegan: false,
    allergens: ['dairy'],
    per_100g: { calories: 48, protein_g: 3.5, carbs_g: 3, fat_g: 1.5, fiber_g: 0, sodium_mg: 320, potassium_mg: 160, phosphorus_mg: 130 },
    gi_index: 20,
    typical_serving_g: 100,
    cost_per_serving_inr: 5,
    prep_time_min: 0,
    condition_flags: { diabetes_safe: true, hypertension_safe: true, ckd_stage3_safe: true, ckd_stage4_safe: true, heart_safe: true },
    ingredients: ['yogurt'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1585937421612-70a19fb1133b?w=500&h=500&fit=crop',
  },
  {
    id: 'buttermilk-chaas',
    name: 'Buttermilk Chaas',
    hindi_name: 'Buttermilk Chaas',
    region: ['north', 'pan-indian'],
    meal_type: ['lunch', 'dinner', 'snack'],
    is_vegetarian: true,
    is_vegan: false,
    allergens: ['dairy'],
    per_100g: { calories: 35, protein_g: 2.5, carbs_g: 2, fat_g: 1, fiber_g: 0, sodium_mg: 310, potassium_mg: 180, phosphorus_mg: 110 },
    gi_index: 15,
    typical_serving_g: 200,
    cost_per_serving_inr: 6,
    prep_time_min: 5,
    condition_flags: { diabetes_safe: true, hypertension_safe: true, ckd_stage3_safe: true, ckd_stage4_safe: true, heart_safe: true },
    ingredients: ['yogurt', 'water', 'salt', 'cumin'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1585937421612-70a19fb1133b?w=500&h=500&fit=crop',
  },

  // Snacks
  {
    id: 'roasted-chana',
    name: 'Roasted Chana',
    hindi_name: 'Roasted Chana',
    region: ['north', 'pan-indian'],
    meal_type: ['snack'],
    is_vegetarian: true,
    is_vegan: true,
    allergens: [],
    per_100g: { calories: 180, protein_g: 10, carbs_g: 20, fat_g: 4, fiber_g: 4, sodium_mg: 200, potassium_mg: 280, phosphorus_mg: 150 },
    gi_index: 38,
    typical_serving_g: 30,
    cost_per_serving_inr: 8,
    prep_time_min: 0,
    condition_flags: { diabetes_safe: true, hypertension_safe: false, ckd_stage3_safe: false, ckd_stage4_safe: false, heart_safe: true },
    ingredients: ['chickpeas', 'salt'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1585937421612-70a19fb1133b?w=500&h=500&fit=crop',
  },
  {
    id: 'makhana-fox-nuts',
    name: 'Makhana Fox Nuts',
    hindi_name: 'Makhana Fox Nuts',
    region: ['north', 'bengali', 'pan-indian'],
    meal_type: ['snack'],
    is_vegetarian: true,
    is_vegan: true,
    allergens: [],
    per_100g: { calories: 106, protein_g: 4.5, carbs_g: 17, fat_g: 1.5, fiber_g: 1.5, sodium_mg: 150, potassium_mg: 140, phosphorus_mg: 110 },
    gi_index: 35,
    typical_serving_g: 30,
    cost_per_serving_inr: 25,
    prep_time_min: 5,
    condition_flags: { diabetes_safe: true, hypertension_safe: true, ckd_stage3_safe: true, ckd_stage4_safe: true, heart_safe: true },
    ingredients: ['fox nuts', 'oil', 'salt'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1585937421612-70a19fb1133b?w=500&h=500&fit=crop',
  },
  {
    id: 'cucumber-slices',
    name: 'Cucumber Slices',
    hindi_name: 'Cucumber Slices',
    region: ['pan-indian'],
    meal_type: ['snack'],
    is_vegetarian: true,
    is_vegan: true,
    allergens: [],
    per_100g: { calories: 15, protein_g: 0.7, carbs_g: 3, fat_g: 0.2, fiber_g: 0.5, sodium_mg: 60, potassium_mg: 140, phosphorus_mg: 20 },
    gi_index: 15,
    typical_serving_g: 100,
    cost_per_serving_inr: 3,
    prep_time_min: 2,
    condition_flags: { diabetes_safe: true, hypertension_safe: true, ckd_stage3_safe: true, ckd_stage4_safe: true, heart_safe: true },
    ingredients: ['cucumber', 'salt'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1585937421612-70a19fb1133b?w=500&h=500&fit=crop',
  },
  {
    id: 'sprouts-salad',
    name: 'Sprouts Salad',
    hindi_name: 'Sprouts Salad',
    region: ['pan-indian'],
    meal_type: ['snack'],
    is_vegetarian: true,
    is_vegan: true,
    allergens: [],
    per_100g: { calories: 52, protein_g: 5, carbs_g: 6, fat_g: 1, fiber_g: 2, sodium_mg: 250, potassium_mg: 200, phosphorus_mg: 100 },
    gi_index: 30,
    typical_serving_g: 150,
    cost_per_serving_inr: 12,
    prep_time_min: 3,
    condition_flags: { diabetes_safe: true, hypertension_safe: true, ckd_stage3_safe: true, ckd_stage4_safe: true, heart_safe: true },
    ingredients: ['mung sprouts', 'lemon', 'salt', 'oil'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1585937421612-70a19fb1133b?w=500&h=500&fit=crop',
  },
  {
    id: 'fruit-bowl-papaya-guava-apple',
    name: 'Fruit Bowl Papaya Guava Apple',
    hindi_name: 'Fruit Bowl Papaya Guava Apple',
    region: ['pan-indian'],
    meal_type: ['snack'],
    is_vegetarian: true,
    is_vegan: true,
    allergens: [],
    per_100g: { calories: 45, protein_g: 0.5, carbs_g: 11, fat_g: 0.2, fiber_g: 1.5, sodium_mg: 30, potassium_mg: 150, phosphorus_mg: 20 },
    gi_index: 40,
    typical_serving_g: 150,
    cost_per_serving_inr: 15,
    prep_time_min: 5,
    condition_flags: { diabetes_safe: true, hypertension_safe: true, ckd_stage3_safe: true, ckd_stage4_safe: true, heart_safe: true },
    ingredients: ['papaya', 'guava', 'apple'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1585937421612-70a19fb1133b?w=500&h=500&fit=crop',
  },
  {
    id: 'boiled-egg',
    name: 'Boiled Egg',
    hindi_name: 'Boiled Egg',
    region: ['pan-indian'],
    meal_type: ['snack'],
    is_vegetarian: false,
    is_vegan: false,
    allergens: ['eggs'],
    per_100g: { calories: 155, protein_g: 13, carbs_g: 1, fat_g: 11, fiber_g: 0, sodium_mg: 140, potassium_mg: 140, phosphorus_mg: 180 },
    gi_index: 0,
    typical_serving_g: 100,
    cost_per_serving_inr: 10,
    prep_time_min: 10,
    condition_flags: { diabetes_safe: true, hypertension_safe: true, ckd_stage3_safe: false, ckd_stage4_safe: false, heart_safe: false },
    ingredients: ['egg', 'salt'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1585937421612-70a19fb1133b?w=500&h=500&fit=crop',
  },
  {
    id: 'peanuts-small-20g',
    name: 'Peanuts Small 20g',
    hindi_name: 'Peanuts Small 20g',
    region: ['pan-indian'],
    meal_type: ['snack'],
    is_vegetarian: true,
    is_vegan: true,
    allergens: ['peanuts'],
    per_100g: { calories: 572, protein_g: 26, carbs_g: 20, fat_g: 49, fiber_g: 6, sodium_mg: 18, potassium_mg: 705, phosphorus_mg: 350 },
    gi_index: 14,
    typical_serving_g: 20,
    cost_per_serving_inr: 5,
    prep_time_min: 0,
    condition_flags: { diabetes_safe: true, hypertension_safe: false, ckd_stage3_safe: false, ckd_stage4_safe: false, heart_safe: true },
    ingredients: ['peanuts', 'salt'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1585937421612-70a19fb1133b?w=500&h=500&fit=crop',
  },
  {
    id: 'walnut-2-pieces',
    name: 'Walnut 2 Pieces',
    hindi_name: 'Walnut 2 Pieces',
    region: ['pan-indian'],
    meal_type: ['snack'],
    is_vegetarian: true,
    is_vegan: true,
    allergens: ['tree nuts'],
    per_100g: { calories: 654, protein_g: 15, carbs_g: 14, fat_g: 65, fiber_g: 3.7, sodium_mg: 2, potassium_mg: 441, phosphorus_mg: 346 },
    gi_index: 15,
    typical_serving_g: 14,
    cost_per_serving_inr: 8,
    prep_time_min: 0,
    condition_flags: { diabetes_safe: true, hypertension_safe: true, ckd_stage3_safe: false, ckd_stage4_safe: false, heart_safe: true },
    ingredients: ['walnut'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1585937421612-70a19fb1133b?w=500&h=500&fit=crop',
  },
  {
    id: 'coconut-water-ckd-careful',
    name: 'Coconut Water Ckd Careful',
    hindi_name: 'Coconut Water Ckd Careful',
    region: ['south', 'pan-indian'],
    meal_type: ['snack'],
    is_vegetarian: true,
    is_vegan: true,
    allergens: [],
    per_100g: { calories: 18, protein_g: 0.9, carbs_g: 3.7, fat_g: 0.2, fiber_g: 0.9, sodium_mg: 105, potassium_mg: 600, phosphorus_mg: 20 },
    gi_index: 35,
    typical_serving_g: 200,
    cost_per_serving_inr: 15,
    prep_time_min: 0,
    condition_flags: { diabetes_safe: true, hypertension_safe: true, ckd_stage3_safe: false, ckd_stage4_safe: false, heart_safe: true },
    ingredients: ['coconut water'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1585937421612-70a19fb1133b?w=500&h=500&fit=crop',
  },
  {
    id: 'green-tea',
    name: 'Green Tea',
    hindi_name: 'Green Tea',
    region: ['pan-indian'],
    meal_type: ['snack'],
    is_vegetarian: true,
    is_vegan: true,
    allergens: [],
    per_100g: { calories: 2, protein_g: 0.5, carbs_g: 0.3, fat_g: 0, fiber_g: 0, sodium_mg: 20, potassium_mg: 30, phosphorus_mg: 5 },
    gi_index: 0,
    typical_serving_g: 200,
    cost_per_serving_inr: 2,
    prep_time_min: 3,
    condition_flags: { diabetes_safe: true, hypertension_safe: true, ckd_stage3_safe: true, ckd_stage4_safe: true, heart_safe: true },
    ingredients: ['green tea leaves', 'water'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1585937421612-70a19fb1133b?w=500&h=500&fit=crop',
  },
  {
    id: 'herbal-kadha',
    name: 'Herbal Kadha',
    hindi_name: 'Herbal Kadha',
    region: ['north', 'pan-indian'],
    meal_type: ['snack'],
    is_vegetarian: true,
    is_vegan: true,
    allergens: [],
    per_100g: { calories: 5, protein_g: 0.2, carbs_g: 1, fat_g: 0, fiber_g: 0, sodium_mg: 30, potassium_mg: 40, phosphorus_mg: 8 },
    gi_index: 0,
    typical_serving_g: 200,
    cost_per_serving_inr: 3,
    prep_time_min: 10,
    condition_flags: { diabetes_safe: true, hypertension_safe: true, ckd_stage3_safe: true, ckd_stage4_safe: true, heart_safe: true },
    ingredients: ['ginger', 'turmeric', 'tulsi', 'water'],
    unsplash_image_url: 'https://images.unsplash.com/photo-1585937421612-70a19fb1133b?w=500&h=500&fit=crop',
  },
]

export function getDishesByMealType(mealType: string): IndianDish[] {
  return INDIAN_FOOD_DB.filter(dish => dish.meal_type.includes(mealType))
}

export function getDishesByRegion(region: string): IndianDish[] {
  return INDIAN_FOOD_DB.filter(dish => dish.region.includes(region))
}

export function getVegetarianDishes(): IndianDish[] {
  return INDIAN_FOOD_DB.filter(dish => dish.is_vegetarian)
}

export function getVeganDishes(): IndianDish[] {
  return INDIAN_FOOD_DB.filter(dish => dish.is_vegan)
}

export function filterByAllergens(dishes: IndianDish[], allergens: string[]): IndianDish[] {
  return dishes.filter(dish => !dish.allergens.some(a => allergens.includes(a)))
}

export function filterByCondition(dishes: IndianDish[], condition: string): IndianDish[] {
  const conditionMap: Record<string, keyof ConditionFlags> = {
    DIABETES: 'diabetes_safe',
    HYPERTENSION: 'hypertension_safe',
    CKD_STAGE_3: 'ckd_stage3_safe',
    CKD_STAGE_4: 'ckd_stage4_safe',
    HEART_DISEASE: 'heart_safe',
  }

  const key = conditionMap[condition]
  if (!key) return dishes

  return dishes.filter(dish => dish.condition_flags[key])
}

export function getDishById(id: string): IndianDish | undefined {
  return INDIAN_FOOD_DB.find(dish => dish.id === id)
}


